### ISSUE TITLE
功能失效，点击输入框无法展开选择器面板

### ISSUE THREAD

**Issue by natee** [liamrad/datepicker-enhanced#3]
### Describe the bug

v2.2.0 版本无法使用，2.2.1正常

### Reproduction

无

### System Info

```Shell
chrome
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by byronogis** [comment]
请提供最小复现示例

**Comment by Kun1605** [comment]
不能用啊

**Comment by Kun1605** [comment]
Cannot destructure property 'emit' of 'instance' as it is null.
TypeError: Cannot destructure property 'emit' of 'instance' as it is null.
    at useModelToggle2 (webpack-internal:///./node_modules/.pnpm/element-plus@2.7.0_vue@3.2.40/node_modules/element-plus/es/hooks/use-model-toggle/index.mjs:44:7)
    at setup (webpack-internal:///./node_modules/.pnpm/element-plus@2.7.0_vue@3.2.40/node_modules/element-plus/es/components/tooltip/src/tooltip2.mjs:64:76)
    at callWithErrorHandling (webpack-internal:///./node_modules/.pnpm/@vue+runtime-core@3.4.21/node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:328:19)
    at setupStatefulComponent (webpack-internal:///./node_modules/.pnpm/@vue+runtime-core@3.4.21/node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:6712:25)
    at setupComponent (webpack-internal:///./node_modules/.pnpm/@vue+runtime-core@3.4.21/node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:6673:36)
    at mountComponent (webpack-internal:///./node_modules/.pnpm/@vue+runtime-core@3.4.21/node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:5225:7)
    at processComponent (webpack-internal:///./node_modules/.pnpm/@vue+runtime-core@3.4.21/node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:5203:9)
    at patch (webpack-internal:///./node_modules/.pnpm/@vue+runtime-core@3.4.21/node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:4878:11)
    at ReactiveEffect.componentUpdateFn [as fn] (webpack-internal:///./node_modules/.pnpm/@vue+runtime-core@3.4.21/node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:5327:11)
    at ReactiveEffect.run (webpack-internal:///./node_modules/.pnpm/@vue+reactivity@3.4.21/node_modules/@vue/reactivity/dist/reactivity.esm-bundler.js:217:19)

**Comment by byronogis** [comment]
可尝试使用 v3 版本, 如仍出现相同情况, 可提供最小复现以方便检查.
